/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BellIcon: typeof import('./src/components/icon/bellIcon.vue')['default']
    Button: typeof import('./src/components/hero/Button.vue')['default']
    Card: typeof import('./src/components/hero/Card.vue')['default']
    Chip: typeof import('./src/components/hero/Chip.vue')['default']
    CloseIcon: typeof import('./src/components/icon/closeIcon.vue')['default']
    CourseInfo: typeof import('./src/components/hero/CourseInfo.vue')['default']
    DashboardIcon: typeof import('./src/components/icon/dashboardIcon.vue')['default']
    DatabaseIcon: typeof import('./src/components/icon/databaseIcon.vue')['default']
    DeleteIcon: typeof import('./src/components/icon/deleteIcon.vue')['default']
    Dropdown: typeof import('./src/components/hero/Dropdown.vue')['default']
    Gallery: typeof import('./src/components/hero/Gallery.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InfoList: typeof import('./src/components/hero/InfoList.vue')['default']
    Input: typeof import('./src/components/hero/Input.vue')['default']
    LoginButton: typeof import('./src/components/LoginButton.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MenuIcon: typeof import('./src/components/icon/menuIcon.vue')['default']
    MenuMobile: typeof import('./src/components/MenuMobile.vue')['default']
    MobileModal: typeof import('./src/components/MobileModal.vue')['default']
    NotificationDrawer: typeof import('./src/components/NotificationDrawer.vue')['default']
    PencilIcon: typeof import('./src/components/icon/pencilIcon.vue')['default']
    PlusIcon: typeof import('./src/components/icon/plusIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/hero/Search.vue')['default']
    SearchIcon: typeof import('./src/components/icon/searchIcon.vue')['default']
    Switch: typeof import('./src/components/hero/Switch.vue')['default']
    Table: typeof import('./src/components/hero/Table.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UserIcon: typeof import('./src/components/icon/userIcon.vue')['default']
    VideoChapterList: typeof import('./src/components/hero/VideoChapterList.vue')['default']
    VideoPlayer: typeof import('./src/components/hero/VideoPlayer.vue')['default']
    WalletIcon: typeof import('./src/components/icon/walletIcon.vue')['default']
  }
}
